- docs/UserGuide.md
Reverts AY2223S1-CS2103T-W16-2/tp#35
> Revert "Add skeleton for user guide"

- docs/UserGuide.md
Update the UG to a skeletal UG for us to work on since the last one was reverted #38 
Credits to @yixiann for doing up this skeletal previously.
> Add skeletal UG

- docs/DeveloperGuide.md
Close #54 
Adds a skeleton to the corresponding sections of the DG. Will be updated soon.
> Add skeletal "user profile" section to DG

- README.md
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/101
> Point CI banners to own project and remove traces of AB3 in README.md

- docs/AboutUs.md
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/99
> Remove boilerplate and update roles in About Us page

- docs/AboutUs.md
- docs/DevOps.md
- docs/Documentation.md
- docs/Logging.md
- docs/SettingUp.md
- docs/Testing.md
- docs/index.md
- docs/team/bryanljx.md
- docs/team/eugenetanwl3881.md
- docs/team/ferusel.md
- docs/team/yixiann.md
> Reformat Markdown files using Prettier

- docs/DeveloperGuide.md
Closes #135 
Added User Stories and formatted use cases for standardization of terms used.
> Add User Stories and Update Use Cases

- docs/DeveloperGuide.md
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/146
> Add value preposition

- docs/DeveloperGuide.md
Closes #139 
- Add use case 5 and 6 (Find items and add tag to item)
- Tag related user stories
> Add use cases and user stories to DG

- docs/UserGuide.md
> Add purpose, scope and audience to UG

- docs/UserGuide.md
Updated UG Command Summary which includes:
- Adding Tag Commands
- Table content formatting
> Update UG Command Summary Table 

- docs/UserGuide.md
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/144
> Change TYPE to UNIT in UserGuide.md

- src/main/java/seedu/foodrem/logic/commands/itemcommands/DeleteCommand.java
- src/test/java/seedu/foodrem/logic/LogicManagerTest.java
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/107
> Rename command word from "delete" to "del"

- src/main/java/seedu/foodrem/logic/commands/generalcommands/ResetCommand.java
- src/main/java/seedu/foodrem/logic/parser/FoodRemParser.java
- src/test/java/seedu/foodrem/logic/commands/itemcommands/EditCommandTest.java
- src/test/java/seedu/foodrem/logic/parser/FoodRemParserTest.java
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/120
> Rename "Clear" to "Reset"

- src/main/java/seedu/foodrem/logic/commands/itemcommands/FindCommand.java
- src/main/java/seedu/foodrem/model/FoodRem.java
- src/main/java/seedu/foodrem/model/tag/UniqueTagList.java
- src/test/java/seedu/foodrem/logic/LogicManagerTest.java
- src/test/java/seedu/foodrem/logic/commands/CommandTestUtil.java
- src/test/java/seedu/foodrem/logic/commands/itemcommands/AddCommandTest.java
- src/test/java/seedu/foodrem/logic/commands/itemcommands/EditCommandTest.java
- src/test/java/seedu/foodrem/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/foodrem/model/UserPrefsTest.java
- src/test/java/seedu/foodrem/model/item/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/foodrem/storage/JsonFoodRemStorageTest.java
- src/test/java/seedu/foodrem/testutil/FoodRemBuilder.java
Rename instances of address book to FoodRem
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/20
> Modify Find item messages and test to match FoodRem instead of AddressBook

- src/main/java/seedu/foodrem/logic/commands/tagcommands/ListTagCommand.java
- src/main/java/seedu/foodrem/logic/commands/tagcommands/TagCommand.java
- src/main/java/seedu/foodrem/logic/commands/tagcommands/UntagCommand.java
- src/main/java/seedu/foodrem/logic/parser/FoodRemParser.java
- src/main/java/seedu/foodrem/model/tag/Tag.java
- src/main/java/seedu/foodrem/model/tag/TagName.java
- src/main/java/seedu/foodrem/ui/ItemCard.java
Closes #114 
Implemented listtag command which will list all available tags from our FilteredTagList in our model.
The tags will be listed in the output (right side of GUI)
Outstanding task:
- Testing
> Add listtag command 

- docs/_dg/UserStories.md
Closes #136 
Adds the Sorting user stories to the DG. Refer to [this document](https://docs.google.com/document/d/1kDJEZUjy2-hNoUon0OQ7hTY5kcZyooB7Hj3U_QrR4r8/edit#).
> Add Sorting user stories to DG

- src/main/java/seedu/foodrem/commons/core/Messages.java
- src/main/java/seedu/foodrem/enums/CommandWord.java
- src/main/java/seedu/foodrem/logic/commands/itemcommands/ViewCommand.java
- src/main/java/seedu/foodrem/logic/parser/FoodRemParser.java
- src/main/java/seedu/foodrem/logic/parser/itemcommandparser/IncrementCommandParser.java
- src/main/java/seedu/foodrem/logic/parser/itemcommandparser/ViewCommandParser.java
- src/main/java/seedu/foodrem/model/item/Item.java
- src/test/java/seedu/foodrem/logic/parser/generalcommandparser/HelpCommandParserTest.java
Closes #112 
Adds a View command to display information about an Item.
> Add View command

- docs/_ug/Features.md
- docs/_ug/features/ItemFeatures.md
- src/main/java/seedu/foodrem/logic/commands/itemcommands/EditCommand.java
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/189
> Update help, edit and delete command

- src/main/java/seedu/foodrem/logic/commands/itemcommands/EditCommand.java
- src/main/java/seedu/foodrem/logic/commands/itemcommands/NewCommand.java
- src/main/java/seedu/foodrem/logic/commands/itemcommands/SortCommand.java
- src/main/java/seedu/foodrem/logic/parser/itemcommandparser/EditCommandParser.java
- src/main/java/seedu/foodrem/logic/parser/itemcommandparser/NewCommandParser.java
- src/main/java/seedu/foodrem/logic/parser/itemcommandparser/SortCommandParser.java
- src/test/java/seedu/foodrem/logic/LogicManagerTest.java
- src/test/java/seedu/foodrem/logic/commands/CommandTestUtil.java
- src/test/java/seedu/foodrem/logic/commands/itemcommands/EditCommandTest.java
- src/test/java/seedu/foodrem/logic/commands/itemcommands/EditItemDescriptorTest.java
- src/test/java/seedu/foodrem/logic/parser/FoodRemParserTest.java
- src/test/java/seedu/foodrem/logic/parser/generalcommandparser/HelpCommandParserTest.java
- src/test/java/seedu/foodrem/logic/parser/itemcommandparser/EditCommandParserTest.java
- src/test/java/seedu/foodrem/logic/parser/itemcommandparser/NewCommandParserTest.java
- src/test/java/seedu/foodrem/logic/parser/tagcommandparser/NewTagCommandParserTest.java
- src/test/java/seedu/foodrem/model/tag/TagTest.java
- src/test/java/seedu/foodrem/testutil/ItemUtil.java
- src/test/java/seedu/foodrem/testutil/TypicalTags.java
Closes #202. Please refer to issue for more details.
> Replace static imports where applicable

- docs/_dg/UserStories.md
> Add missing user stories to DG

- .markdownlint.json
- docs/_sass/toc.scss
Just a small PR to improve the code quality.
> Update miscellaneous items

- src/main/java/seedu/foodrem/logic/commands/tagcommands/RenameTagCommand.java
- src/main/java/seedu/foodrem/storage/FoodRemStorage.java
- src/main/java/seedu/foodrem/storage/JsonFoodRemStorage.java
- src/main/java/seedu/foodrem/storage/JsonSerializableFoodRem.java
- src/main/java/seedu/foodrem/storage/Storage.java
- src/main/java/seedu/foodrem/storage/StorageManager.java
- src/test/data/JsonFoodRemStorageTest/invalidAndValidItemFoodRem.json
- src/test/data/JsonFoodRemStorageTest/invalidItemFoodRem.json
- src/test/data/JsonSerializableFoodRemTest/duplicateItemFoodRem.json
- src/test/data/JsonSerializableFoodRemTest/duplicateTagFoodRem.json
- src/test/data/JsonSerializableFoodRemTest/invalidItemFoodRem.json
- src/test/data/JsonSerializableFoodRemTest/invalidTagFoodRem.json
- src/test/data/JsonSerializableFoodRemTest/typicalFoodRem.json
- src/test/java/seedu/foodrem/logic/commands/tagcommands/RenameTagCommandTest.java
- src/test/java/seedu/foodrem/storage/JsonFoodRemStorageTest.java
- src/test/java/seedu/foodrem/storage/JsonSerializableFoodRemTest.java
- src/test/java/seedu/foodrem/testutil/TypicalTags.java
Edit storage to also store tag list.
- Add storage for tag list 
- Remove traces of address book in storage pkg
- Update test data
- Update test cases for FoodRem storage
> Add storage for tag list

- build.gradle
Enabled assertions in build.gradle which is required for Week 10
> Enable assertions for Week 10 Team Task

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/_dg/Implementation.md
- docs/_dg/TaggingFunctionality.md
- docs/_sass/foodrem.scss
- docs/_sass/minima/_base.scss
Closes #245.
Closes #246.
Closes #247.
Closes #248.
Closes #249.
> Fix styling-related bugs in markdown files

- .github/workflows/build.yml
Refer to [StackOverflow](https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at) for explanation.
Also fixed a typo.
> Fix JAR file CD release time

- docs/UserGuide.md
- docs/_ug/Commands.md
- docs/_ug/commandSummary/ItemCommands.md
Closes #259.
Also reformatted some markdown files to fix style issues.
> Fix website compile error

- docs/SettingUp.md
- docs/Testing.md
- docs/_glossary/.markdownlint.json
- docs/_glossary/Flag.md
- docs/_glossary/Placeholder.md
- docs/_ug/HowToUseUserGuide.md
- docs/_ug/ItemsTags.md
- docs/_ug/QuickStart.md
- docs/_ug/Troubleshooting.md
- docs/_ug/TryingFirstCommand.md
- docs/_ug/UsingFoodRem.md
- docs/_ug/commandSummary/itemCommands/find.md
- docs/_ug/commands/GeneralCommands.md
- docs/_ug/commands/ItemCommands.md
- docs/_ug/commands/TagCommands.md
- docs/_ug/placeholders/PRICE.md
> Reformat markdown files

- docs/_sass/foodrem.scss
Also style the checkboxes to match the default values.
Closes #256.
> Remove duplicate list marker in task lists

- docs/_dg/UseCases.md
Use Cases Headers are currently messed up due to formatting. This will fix it
> Small Fixes for DG Headers for Use Cases

- src/main/java/seedu/foodrem/logic/commands/itemcommands/DeleteCommand.java
- src/main/java/seedu/foodrem/logic/commands/itemcommands/ViewCommand.java
> Fix index out of bound bug and standardise naming of index across item command

- src/main/java/seedu/foodrem/model/item/ItemPrice.java
- src/main/java/seedu/foodrem/model/item/ItemQuantity.java
- src/test/java/seedu/foodrem/model/item/ItemTest.java
> Add item tests and fix hashcode

- docs/_sass/admonitions.scss
- docs/_ug/Placeholders.md
> Parse markdown in placeholders table + fix style bug

- .github/workflows/build.yml
> Fix continuous deployment names

- docs/_sass/foodrem.scss
Closes #332.
Also adjusts spacings around headings for better readability.
> Update website styling

- docs/_ug/Layout.md
Fixes the bug introduced in #335.
> Fix broken link fragment for GUI

- docs/UserGuide.md
Simple fix for Jekyll compile error
> Website Hot Fix

- docs/_ug/commands/StatisticsCommands.md
- src/main/java/seedu/foodrem/model/item/ItemPrice.java
- src/main/java/seedu/foodrem/views/ItemView.java
Hotfixes for the item's price and cost representation. Also updates the stats section in the UG.
> Fix stats command

- src/main/java/seedu/foodrem/commons/util/StringUtil.java
- src/main/java/seedu/foodrem/model/item/ItemName.java
- src/main/java/seedu/foodrem/model/item/ItemRemark.java
- src/main/java/seedu/foodrem/model/item/ItemUnit.java
> Fix sorting by name

- docs/_ug/Installation.md
- docs/_ug/TryingFirstCommand.md
- docs/_ug/commands/ItemCommands.md
- docs/_ug/placeholders/INDEX.md
- docs/_ug/placeholders/PRICE.md
- docs/_ug/placeholders/QUANTITY.md
- docs/_ug/placeholders/UNIT.md
Fix UG mistakes highlighted by testers in PE Dry Run
Closes #405 
Closes #401 
Closes #403 
Closes #394 
Closes #388 
Closes #384 
Closes #383
> Fix UG Bugs reported in PED

- src/main/java/seedu/foodrem/logic/parser/FoodRemParser.java
- src/main/java/seedu/foodrem/logic/parser/statsparser/StatsCommandParser.java
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/414
> Use stats parser to restrict command arguments

- src/main/java/seedu/foodrem/views/TagView.java
Fixes: https://github.com/AY2223S1-CS2103T-W16-2/tp/issues/436
> Fix getColor for tags

- .github/workflows/check-ppp-edited.yml
- cli-test/ppp-checker/check-ppp-is-complete.sh
- cli-test/ppp-checker/check-ppp-is-present.sh
Only checks that `PR#XXX` substring is present now.
> Make PPP checking more lenient

- src/main/java/seedu/foodrem/logic/commands/tagcommands/TagCommandUtil.java
- src/main/java/seedu/foodrem/logic/parser/tagcommandparser/RenameTagCommandParser.java
- src/main/java/seedu/foodrem/logic/parser/tagcommandparser/TagCommandParser.java
- src/main/java/seedu/foodrem/logic/parser/tagcommandparser/UntagCommandParser.java
- src/main/java/seedu/foodrem/model/tag/Tag.java
- src/main/java/seedu/foodrem/model/tag/TagName.java
- src/main/java/seedu/foodrem/model/tag/TagNameContainsKeywordsPredicate.java
- src/main/java/seedu/foodrem/model/tag/exceptions/DuplicateTagException.java
- Remove duplicated code that could been fetched from ParserUtil
- Added more assertions for defensive coding
- Add Javadocs missed out
> Improve Code Quality of Tag Commands

- docs/team/eugenetanwl3881.md
Updated PPP PR links to standardize formatting
> Update PPP PR formatting

- src/main/java/seedu/foodrem/commons/enums/CommandType.java
- src/main/java/seedu/foodrem/logic/commands/generalcommands/HelpCommand.java
- src/main/java/seedu/foodrem/views/StatsView.java
- src/test/java/seedu/foodrem/logic/commands/generalcommands/HelpCommandTest.java
- src/test/java/seedu/foodrem/logic/parser/generalcommandparser/HelpCommandParserTest.java
Add full stop to help message for individual commands
Convert stats amount wasted to 2.d.p
Ensure consistency in ug and help command
Fix out of bound error in stats when there are no items in foodrem
> Fix minor errors

- docs/team/ferusel.md
> Update PPP for ferusel

- docs/_ug/commands/ItemCommands.md
Closes #380 
This issue is a non-issue as the user used the command wrongly. However, we should include a small warning in the UG to avoid this misconception.
> Add warning for find command
